[[plugins]]
repo = 'Shougo/neocomplete.vim'
if   =  '''! has('nvim')'''
on_i = 1
hook_add = '''
  let g:neocomplete#enable_at_startup = 1 
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#enable_auto_select = 1

  if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {} 
  endif
  let g:neocomplete#force_overwrite_completefunc = 1
  let g:neocomplete#force_omni_input_patterns.c =
        \ '[^.[:digit:] *\t]\%(\.\|->\)\w*'
  let g:neocomplete#force_omni_input_patterns.cpp =
        \ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
'''


[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_source = ['neocomplete.vim']


[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = 'cpp'
if  = '''executable('clang')'''
hook_add = '''
  let g:clang_auto = 0
  let g:clang_complete_auto = 0
  let g:clang_auto_select = 1
  let g:clang_use_library = 1

  let g:clang_cpp_completeopt = 'menuone'
  let g:clang_exec = 'clang'
  let g:clang_cpp_options = '-std=c++1z -stdlib=libc++'
  let g:clang_format_exec = 'clang-format'
'''


[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'


[[plugins]]
repo   = 'Shougo/unite.vim'
depens = "neomru.vim"
hook_add = '''
    let g:unite_source_session_enable_auto_save = 1
    let g:unite_source_history_yank_enable = 1
    let g:unite_source_file_mru_limit = 1000
    let g:unite_enable_start_insert = 1

    nnoremap <C-@> :Unite -direction=botright window buffer file file_mru<CR>
    inoremap <C-@> <ESC>:Unite -direction=botright window buffer file file_mru<CR>
    nnoremap <C-\> :Unite -direction=botright window buffer file file_mru<CR>
    inoremap <C-\> <ESC>:Unite -direction=botright window buffer file file_mru<CR>
    nnoremap <C-g> :Unite grep -auto-preview -auto-resize<CR><CR>

    function! s:unite_my_settings()
      imap <buffer> <ESC><ESC><ESC> <Plug>(unite_exit)
      nmap <buffer> <ESC><ESC><ESC> <Plug>(unite_exit)
      nnoremap <silent><buffer><expr> v unite#do_action('vsplit')
      nnoremap <silent><buffer><expr> s unite#do_action('split')
    endfunction
    augroup UniteMySettings
      autocmd FileType unite call s:unite_my_settings()
    augroup END
'''


[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']


[[plugins]]
repo      = 'Shougo/unite-outline'
on_source = ['unite.vim']
hook_add = '''
    command! -nargs=0 Outline call Outline()
    function! Outline()
      :Unite -vertical -winwidth=30 outline
    endfunction
'''

[[plugins]]
repo =  'kmnk/vim-unite-giti'
on_source = ['unite.vim']

[[plugins]]
repo =  'tsukkee/unite-tag'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/neoyank.vim'
on_source = ['unite.vim']

[[plugins]]
repo =  'rhysd/wandbox-vim'
on_ft = ["c", "cpp"]


[[plugins]]
repo =  'rhysd/vim-clang-format'
on_ft = ["c", "cpp"]


[[plugins]]
repo =  'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo =  'fatih/vim-go'
on_ft = 'go'
hook_add = '''
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1
'''


[[plugins]]
repo =  'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
  let g:tex_flavor='latex'
  let g:vimtex_latexmk_options = '-pdfdvi'
  let g:tex_conceal = ''
  let g:vimtex_imaps_enabled = 0
  " viewer
  let g:vimtex_view_general_viewer
  \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
  let g:vimtex_view_general_options = '@line @pdf @tex'
  autocmd FileType tex syntax spell toplevel
'''
