[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1


[[plugins]]
repo   = 'Shougo/unite.vim'
hook_add = '''
    let g:unite_source_session_enable_auto_save = 1
    let g:unite_source_history_yank_enable = 1
    let g:unite_source_file_mru_limit = 1000
    let g:unite_enable_start_insert = 1

    nnoremap <C-\> :Unite -direction=botright window buffer file file_mru<CR>
    inoremap <C-\> <ESC>:Unite -direction=botright window buffer file file_mru<CR>
    nnoremap <C-g> :Unite grep -auto-preview -auto-resize<CR><CR>

    function! s:unite_my_settings()
      imap <buffer> <ESC><ESC><ESC> <Plug>(unite_exit)
      nmap <buffer> <ESC><ESC><ESC> <Plug>(unite_exit)
      nnoremap <silent><buffer><expr> v unite#do_action('vsplit')
      nnoremap <silent><buffer><expr> s unite#do_action('split')
    endfunction
    augroup UniteMySettings
      autocmd FileType unite call s:unite_my_settings()
    augroup END
'''


[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']


[[plugins]]
repo      = 'Shougo/unite-outline'
on_source = ['unite.vim']
hook_add = '''
    command! -nargs=0 Outline call Outline()
    function! Outline()
      :Unite -vertical -winwidth=30 outline
    endfunction
'''

[[plugins]]
repo =  'kmnk/vim-unite-giti'
on_source = ['unite.vim']

[[plugins]]
repo =  'tsukkee/unite-tag'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/neoyank.vim'
on_source = ['unite.vim']

[[plugins]]
repo =  'rhysd/wandbox-vim'
on_ft = ["c", "cpp"]


[[plugins]]
repo =  'rhysd/vim-clang-format'
on_ft = ["c", "cpp"]


[[plugins]]
repo =  'cespare/vim-toml'
on_ft = 'toml'
